version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27077:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - ramadan-network

  backend:
    build: ./backend
    ports:
      - "5050:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/ramadan_quiz
      - PORT=5000
      - JWT_SECRET=ramadan_2026_top_secret_key
      - ADMIN_USER=admin
      - ADMIN_PASS=ramadan2026
    depends_on:
      - mongodb
    networks:
      - ramadan-network

  frontend:
    build: ./frontend
    ports:
      - "3030:3000"
    depends_on:
      - backend
    networks:
      - server
      - ramadan-network

networks:
  server:
    external: true
  ramadan-network:
    driver: bridge

volumes:
  mongo-data:
